# Обработка ошибок

## try-catch-finally?

```js
try {
    // код
} catch(error) {
    // обработка ошибки
}
```

Выполняется блок `try`, если в нем нет ошибок блок `catch` игнорируется и выполнение скрипта продолжается. В противном случае выполнение блока `try` прекращается и начинает выполнятся блок `catch`, при этом в переменную `error` передается объект ошибки для анализа.

## Error object?